# Generated by Django 4.1.3 on 2022-11-27 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('NE', 'Новость'), ('AR', 'Статья')], max_length=2)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('header', models.CharField(default='Unnamed', max_length=155)),
                ('body', models.TextField(default='Text')),
                ('rate_post', models.IntegerField(db_column='rating', default=0)),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.authors')),
                ('name_category', models.ManyToManyField(through='news.Post_Category', to='news.categories')),
            ],
        ),
        migrations.AddField(
            model_name='post_category',
            name='posts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.posts'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.TextField(max_length=1500)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('rate_comment', models.IntegerField(db_column='rating', default=0)),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
