# Generated by Django 4.1.3 on 2022-12-10 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_appointment_subscribersusers_categories_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='subscribers',
            new_name='sub_user',
        ),
        migrations.RenameField(
            model_name='subscribersusers',
            old_name='id_categories',
            new_name='categories',
        ),
    ]
