# Generated by Django 4.1.4 on 2023-01-31 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_subscribers_categories_sub_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='cat_name_en_us',
            field=models.CharField(help_text='category name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='cat_name_ru',
            field=models.CharField(help_text='category name', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='cat_name',
            field=models.CharField(help_text='category name', max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en_us', models.CharField(max_length=100, null=True)),
                ('name_ru', models.CharField(max_length=100, null=True)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kinds', to='news.categories', verbose_name='This is the help text')),
            ],
        ),
    ]
